language: en

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: debugger.Debugger
  prefix: LOGGING READY
  color: green
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: debugger.Debugger
- name: DIETClassifier
  epochs: 20
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
  - name: MappingPolicy
